services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_GOOGLE_CLIENT_ID: ${NEXT_PUBLIC_GOOGLE_CLIENT_ID}
    container_name: hmmeeting
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env.production
    volumes:
      - sqlite_data:/app/data
    environment:
      - DATABASE_URL=file:/app/data/prod.db

volumes:
  sqlite_data:
